"""create_tables

Revision ID: 014817d507cb
Revises: 
Create Date: 2026-05-01 12:25:41.798181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014817d507cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('expedient_id', sa.String(), nullable=False),
    sa.Column('publicacio_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(), nullable=False),
    sa.Column('organ', sa.String(), nullable=False),
    sa.Column('pressupost', sa.Float(), nullable=False),
    sa.Column('codi_expedient', sa.String(), nullable=False),
    sa.Column('fase', sa.String(), nullable=False),
    sa.Column('data_publicacio', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('expedient_id')
    )
    op.create_table('documents',
    sa.Column('expedient_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('mida_kb', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['expedient_id'], ['tenders.expedient_id'], ),
    sa.PrimaryKeyConstraint('expedient_id', 'doc_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expedient_id', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('detall', sa.Text(), nullable=False),
    sa.Column('paraules_clau_trobades', sa.Text(), nullable=False),
    sa.Column('penalitzacions', sa.Text(), nullable=False),
    sa.Column('recomanacio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['expedient_id'], ['tenders.expedient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('documents')
    op.drop_table('tenders')
    # ### end Alembic commands ###
