"""add max_licitacions to filter_configs

Revision ID: 1830436449a2
Revises: 0001
Create Date: 2026-05-09 20:01:55.220738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1830436449a2'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_configs', sa.Column('max_licitacions',
                  sa.Integer(), nullable=False, server_default='20'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_configs', 'max_licitacions')
    # ### end Alembic commands ###
