"""fase_j1_score_columns_and_tender_documents

Revision ID: 32dad608b433
Revises: 2b4f9c1e3d7a
Create Date: 2026-05-12 22:41:58.525367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dad608b433'
down_revision: Union[str, None] = '2b4f9c1e3d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expedient_id', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('comentari_llm', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expedient_id'], ['tenders.expedient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_expedient_id'), 'tender_documents', ['expedient_id'], unique=False)
    op.add_column('tenders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenders', sa.Column('score_total', sa.Integer(), nullable=True))
    op.add_column('tenders', sa.Column('score_traffic_light', sa.String(length=10), nullable=True))
    op.add_column('tenders', sa.Column('score_detall', sa.Text(), nullable=True))
    op.add_column('tenders', sa.Column('recomendacio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'recomendacio')
    op.drop_column('tenders', 'score_detall')
    op.drop_column('tenders', 'score_traffic_light')
    op.drop_column('tenders', 'score_total')
    op.drop_column('tenders', 'created_at')
    op.drop_index(op.f('ix_tender_documents_expedient_id'), table_name='tender_documents')
    op.drop_table('tender_documents')
    # ### end Alembic commands ###
